export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_ID = 'FETCH_MOVIE_ID';
export const REMOVE_SELECTED_MOVIE = 'REMOVE_SELECTED_MOVIE';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
